# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-posted_time']},
        ),
        migrations.AddField(
            model_name='image',
            name='posted_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
