# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180717_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['posted_time']},
        ),
    ]
