# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180717_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='decription',
            new_name='description',
        ),
    ]
